# sudo: required

services:
  # - docker

language: node_js
node_js:
  - "6"

# safelist
branches:
  only:
    - master
    - develop

before_install:
  # - docker pull gregdaynes/rmq-exchange
  # or docker build...
  # - docker run ...
  # - docker ps -a
  # - docker run ... test

after_success:
    # push to docker
